#!/bin/bash
# List all ssh hosts from bash history
# requires package source-highlight

# Delimit items ONLY for newline (in for loops for example)
IFS="
"
echo ""
counter=0
sshlMatches=`less ~/.bash_history | grep "^ssh " | grep "@\w" | sed "s/ssh //g" | sed 's/ *$//g' | grep -v " \"" |grep -v " -"| grep -v "^-" | sed 's/"//g' | awk -F"@" '{print $2 " " $1}' |awk -F" " '{print $1 " " $3 " " $2}' | sort -u`
rowcount=`echo sshlMatches|wc -l`
if [ $rowcount == 0 ]
then
	echo "No ssh commands in history..."
else 
	if [[ "$1" == ?(+|-)+([0-9]) ]]
	then
		line="$1"
	else
		prevServer=""
		prevComment=""
		serverCount=1
		for current in $sshlMatches
		do
			server=`echo $current | awk -F" " '{print $1}'`
			if [ "$prevServer" != "" ]
			then
				if [ "$server" == "$prevServer" ]
				then
				  tput bold && tput setaf 7
					if [ $serverCount == 1 ]
          then
            echo "    $prevServer"
          fi
					tput sgr0
					printf "%-3s    %s \n" $counter $prevUser
					serverCount=`expr $serverCount + 1`
				else
					if [ $serverCount == 1 ]
					then
						printf "%-3s" $counter
						tput bold && tput setaf 7
						printf " %s" $prevServer
						tput sgr0
						printf " %s" $prevUser
						tput bold && tput setaf 1
						printf " %s\n" $prevComment
						tput sgr0
					else
						printf "%-3s    %s \n" $counter $prevUser
					fi
					serverCount=1
				fi
			fi
			# remember loop count
			counter=`expr $counter + 1`
			prevServer="$server"
			prevUser=`echo $current | awk -F" " '{print $2}'`
			prevComment=`echo $current | awk -F"#" '{print $2}'`
		done

		tput sgr0

		echo -e $NC
		echo ""
		read -p "Run SSH command from history (negative number to remove, prefix with 'c' to comment):" line
	fi
	match=0
	if [[ "$line" == ?(+|-)+([0-9]) ]]
	then
		counter=1
		for current in $sshlMatches
		do
			server=`echo $current | awk -F" " '{print $2 "@" $1}'`
			if [ $counter == $line ]
			then
				match=$current
				break
			elif [ `expr 0 - $line` == $counter ]
			then 
				match=-1
				sed -i "/^ssh $server$/d" ~/.bash_history
				break
			fi	
			counter=`expr $counter + 1`
		
		done
	elif [[ "$line" == ?(c)+([0-9])+( )+([a-zA-Z0-9]) ]]
	then
		counter=1
		for current in $sshlMatches
		do
			server=`echo $current | awk -F" " '{print $2 "@" $1}'`
			lineNumber=`echo $line | awk -F" " '{print $1}'`
			comment=`echo $line | awk -F" " '{print $2}'`
			if [ "$lineNumber" == "c$counter" ]
			then 
				match=-2
				sed -i "s/^ssh $server.*/ssh $server #$comment/g" ~/.bash_history
				break
			fi	
			counter=`expr $counter + 1`
		done
	fi
	if [ $match == 0 ]
	then
		echo "You have entered an incorrect value. Examples:"
		echo " 3         => Login to server with index 3"
		echo "-3         => Remove server with index 3"
		echo "c3 ProdSrv => Add comment 'ProdServer' to server with index 3"
		echo
		read -p "Press enter to try again..."
		sshh
	elif [ $match == -1 ]
	then
		echo "Removed ssh command from ssh history: ssh $current"
		sshh
	elif [ $match == -2 ]
	then
		echo "Added comment to ssh login"
		sshh
	else 
		# convert "<server> <user>" to "<user>@<server>"
		server=`echo $match | awk -F" " '{print $1}'`
		user=`echo $match | awk -F" " '{print $2}'`
		user=`echo $user| sed 's/\\\\\\\/\\\/g'`
		echo "ssh $server -l $user"
		ssh $server -l $user
	fi
fi

IFS=$OIFS
